### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by l29utp0** [Lacerkage/PastaBot#2]
- Board whitelist - list of boards the bot will get threads from, ignoring others.
- Posting timer - being able to chose posting interval.
- Be website agnostic - can work with any jschan/pleroma website.

**Comment by Lacerkage** [comment]
> - Posting timer - being able to chose posting interval.
> - Be website agnostic - can work with any jschan/pleroma website.

Added some environment variables: `UPDATE_TIME` (in seconds), `FEDIVERSE_INSTANCE` and `JSCHAN_WEBSITE`, so that should do it

**Comment by loynet** [comment]
Now that #4 was merged, I think we have implemented every suggestion. Nice! 

The README has to be updated since it mentions [ptchan.org](https://ptchan.org) directly which may cause confusion. 
Fediverse includes things like Mastodon and a lot more. I’m not sure if this project will be compatible with all of them so that probably should be changed too.
